server:
  port: 9090

spring:
  application:
    name: halo-demo
  profiles:
    active: my

## ?????
  datasource:
    url: jdbc:mysql://localhost:3306/halo_ry?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: mdd05081212
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      connection-timeout: 30000




# xxl-job??
xxl:
  job:
    admin:
      # ????????? [??]???????????????????????????????????"???????"?"??????"???????????
#      addresses: http://mplat-job-beta.speiyou.cn
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # ???AppName [??]??????????????????????
      #      appname: ${spring.application.name}
      appname: ${spring.application.name}
      # ???IP [??]???????????IP????????????IP??IP????Host?????????????? "?????" ? "???????????"?
      ip:
      # ?????? [??]?????0???????????9999?????????????????????????
      port:
      # ??????????????? [??] ????????????????????????
      logpath: ./data/applogs/xxl-job/jobhandler
      # ????????? [??] ????3?????????Log???????????????
      logretentiondays: 10
    # ?????TOKEN [??]???????
    accessToken: default_token


mybatis-plus:
  # ??mapper?xml????
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.halo.demo.entity
  configuration:
    # ??????
    map-underscore-to-camel-case: true
    # ?????SQL??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
