server:
  port: 9090
  tomcat:
    uri-encoding: utf-8


spring:
  application:
    name: halo-demo
  profiles:
    active: my


## 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/halo_ry?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: mdd05081212
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      connection-timeout: 30000

  ## 配置远程调用feignClient
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            requestInterceptors:
              - com.halo.demo.config.XesOriginRequestInterceptor


## 远程服务配置
remote:
  server:
    lesson:
      basePath: lesson-beta-inner.speiyou.cn



# xxl-job配置
xxl:
  job:
    admin:
      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#      addresses: http://mplat-job-beta.speiyou.cn
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      #      appname: ${spring.application.name}
      appname: ${spring.application.name}
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port:
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ./data/applogs/xxl-job/jobhandler
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      logretentiondays: 10
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token


mybatis-plus:
  # 指定mapper的xml文件位置
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.halo.demo.entity
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 控制台显示SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
